import type { Metadata } from "next";
import { Clock, Mail, MapPin, Phone } from "lucide-react";
import { Container, Section, SectionHeading } from "@/components/core/container";

export const metadata: Metadata = { title: "Contact", description: "Contact Grey School Academy or arrange a visit." };
const input="focus-ring mt-2 min-h-12 w-full border border-hairline bg-cream px-4 text-sm placeholder:text-slate/60";
export default function ContactPage(){ return <>
  <section className="bg-midnight py-24 text-white lg:py-36"><Container><p className="eyebrow text-sage">Contact Grey</p><h1 className="page-title max-w-4xl">A conversation is a good place to begin.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Whether you are planning a visit, considering an application or need practical information, we will make sure you reach the right person.</p></Container></section>
  <Section><Container><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr] lg:gap-24"><div><h2 className="font-sans text-3xl font-semibold text-midnight">Grey School Academy</h2><div className="mt-8 space-y-7 text-sm"><div className="flex gap-4"><MapPin className="h-5 w-5 text-growth"/><address className="not-italic leading-6 text-slate">18 Grey Lane<br/>Westbrook, Nairobi<br/>Kenya</address></div><div className="flex gap-4"><Phone className="h-5 w-5 text-growth"/><a href="tel:+254200000000">+254 (0)20 000 0000</a></div><div className="flex gap-4"><Mail className="h-5 w-5 text-growth"/><a href="mailto:hello@greyschool.ac.ke">hello@greyschool.ac.ke</a></div><div className="flex gap-4"><Clock className="h-5 w-5 text-growth"/><p className="leading-6 text-slate">Monday–Friday<br/>07:30–17:00</p></div></div><div className="mt-10 border-l-2 border-growth pl-6"><p className="font-semibold">Admissions</p><p className="mt-2 text-sm leading-6 text-slate">Maya Wanjiku, Registrar<br/><a className="text-scholastic" href="mailto:admissions@greyschool.ac.ke">admissions@greyschool.ac.ke</a></p></div></div>
  <div><SectionHeading eyebrow="Send an enquiry" title="How can we help?"/><form className="mt-10 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">First name<input className={input} name="firstName" autoComplete="given-name" required/></label><label className="text-sm font-semibold">Last name<input className={input} name="lastName" autoComplete="family-name" required/></label><label className="text-sm font-semibold">Email<input className={input} type="email" name="email" autoComplete="email" required/></label><label className="text-sm font-semibold">I’m interested in<select className={input} name="interest"><option>Admissions</option><option>Book a visit</option><option>General enquiry</option><option>Current parent query</option></select></label><label className="text-sm font-semibold sm:col-span-2">Message<textarea className={`${input} min-h-36 py-3`} name="message" required/></label><div className="sm:col-span-2"><button className="focus-ring min-h-12 bg-midnight px-7 font-sans text-sm font-bold text-white transition hover:bg-scholastic">Send enquiry</button><p className="mt-3 text-xs text-slate">We aim to reply within two school days.</p></div></form></div></div></Container></Section>
  <section id="visit" className="bg-sage/60"><Container className="grid gap-10 py-20 lg:grid-cols-[1fr_1fr] lg:items-center"><div><SectionHeading eyebrow="Visit Grey" title="See the school in motion." intro="A visit includes time in lessons, a campus tour and an unhurried conversation with admissions."/></div><form className="bg-cream p-7 shadow-soft sm:p-9"><h3 className="font-sans text-2xl font-semibold">Request a visit</h3><label className="mt-6 block text-sm font-semibold">Your email<input className={input} type="email" required/></label><label className="mt-5 block text-sm font-semibold">Preferred date<input className={input} type="date" required/></label><button className="focus-ring mt-6 min-h-12 w-full bg-growth px-6 font-bold text-white hover:bg-midnight">Request a visit</button></form></Container></section>
  </> }
