import type { Metadata } from "next";
import { Check, Download } from "lucide-react";
import { PageHero } from "@/components/editorial/page-hero";
import { FAQ } from "@/components/editorial/faq";
import { Container, Section, SectionHeading } from "@/components/core/container";
import { Button } from "@/components/core/button";
import { faqs, images } from "@/data/site";

export const metadata: Metadata = { title: "Admissions", description: "Plan your family's admissions journey to Grey School Academy." };
export default function AdmissionsPage() { const steps = [["Discover","Explore our approach and decide whether Grey feels right."],["Visit","See teaching in action and meet the people behind the school."],["Apply","Complete a clear online application and submit recent reports."],["Meet","Your child joins an age-appropriate, friendly session."],["Offer","We share decisions promptly and answer every practical question."],["Welcome","A careful transition begins well before the first morning."]]; return <>
  <PageHero eyebrow="Admissions" title="Your journey starts here." intro="Choosing a school is a significant family decision. We make the process personal, transparent and unhurried enough for you to ask what really matters." image={images.campus} imageAlt="Welcoming school campus and grounds" />
  <Section><Container><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><SectionHeading eyebrow="Why Grey" title="A high-expectation school with a human scale." intro="Families choose Grey for teaching that is precise, pastoral care that is genuinely personal, and a childhood rich in friendship, activity and meaningful responsibility."/><div className="lg:pt-24"><ul className="space-y-4">{["Every pupil known by the adults who teach them","A coherent academic journey from ages 4 to 11","A broad programme of sport, arts, clubs and outdoor learning","Clear, consistent communication with families"].map(x=><li key={x} className="flex gap-4 border-b border-hairline pb-4"><Check className="h-5 w-5 shrink-0 text-growth"/><span>{x}</span></li>)}</ul></div></div></Container></Section>
  <Section className="bg-sage/55"><Container><SectionHeading eyebrow="Entry points" title="A thoughtful beginning at every age."/><div className="mt-14 grid gap-px bg-growth/20 md:grid-cols-3"><div className="bg-cream p-8 md:p-10"><span className="text-xs font-bold text-growth">PRIMARY ENTRY</span><h3 className="mt-5 font-sans text-3xl font-semibold">Reception</h3><p className="mt-4 leading-7 text-slate">For children turning four before the start of the academic year. Most places are offered here.</p></div><div className="bg-cream p-8 md:p-10"><span className="text-xs font-bold text-growth">OCCASIONAL PLACES</span><h3 className="mt-5 font-sans text-3xl font-semibold">Years 1–5</h3><p className="mt-4 leading-7 text-slate">Places arise from time to time. We welcome enquiries and maintain a considered waiting list.</p></div><div className="bg-midnight p-8 text-white md:p-10"><span className="text-xs font-bold text-sage">NEXT OPEN MORNING</span><h3 className="mt-5 font-sans text-3xl font-semibold">18 September</h3><p className="mt-4 leading-7 text-white/65">Tour classrooms, hear from our Headteacher and speak with current pupils and parents.</p><Button href="/contact#visit" variant="light" className="mt-7">Reserve a place</Button></div></div></Container></Section>
  <Section><Container><SectionHeading eyebrow="The admissions journey" title="Six clear steps from hello to welcome."/><div className="relative mt-16 grid gap-y-12 md:grid-cols-3 lg:grid-cols-6 before:absolute before:left-0 before:right-0 before:top-6 before:hidden before:h-px before:bg-hairline md:before:block">{steps.map(([name,copy],i)=><div key={name} className="relative pr-6"><span className="relative z-10 grid h-12 w-12 place-items-center rounded-full bg-midnight text-xs font-bold text-white">0{i+1}</span><h3 className="mt-6 font-sans text-lg font-semibold">{name}</h3><p className="mt-3 text-sm leading-6 text-slate">{copy}</p></div>)}</div></Container></Section>
  <Section className="bg-porcelain"><Container><div className="grid gap-12 lg:grid-cols-2 lg:gap-24"><div><SectionHeading eyebrow="Fees" title="Clear from the outset." intro="The figures below are illustrative while final 2026/27 fees are confirmed. Our admissions team will always provide a complete schedule before application."/><button className="focus-ring mt-8 inline-flex items-center gap-3 text-sm font-bold text-scholastic"><Download className="h-4 w-4"/>Download fee schedule</button></div><div className="border-t border-midnight"><div className="flex justify-between border-b border-hairline py-5"><span>Reception–Year 2</span><strong>KSh 000,000 / term</strong></div><div className="flex justify-between border-b border-hairline py-5"><span>Years 3–6</span><strong>KSh 000,000 / term</strong></div><p className="mt-5 text-xs leading-5 text-slate">Fees are placeholders pending approval. Lunch, most clubs and curriculum trips will be itemised clearly in the published schedule.</p></div></div></Container></Section>
  <Section><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Questions" title="Good things to ask."/><FAQ items={faqs}/></div></Container></Section>
  <section id="apply" className="bg-growth text-white"><Container className="grid gap-10 py-20 lg:grid-cols-[1.3fr_.7fr] lg:items-center"><div><h2 className="section-title">Ready when you are.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/75">Speak with Maya in admissions, arrange a visit or begin an application. There is no pressure—only clear help.</p></div><div className="flex flex-col gap-3"><Button href="/contact#visit" variant="light">Book a visit</Button><Button href="/contact" variant="outline">Contact admissions</Button></div></Container></section>
  </>; }
