import type { Metadata } from "next";
import Image from "next/image";
import { CurriculumExplorer } from "@/components/home/curriculum-explorer";
import { PageHero } from "@/components/editorial/page-hero";
import { AdmissionsPanel } from "@/components/editorial/admissions-panel";
import { Container, Section, SectionHeading } from "@/components/core/container";
import { images, stages } from "@/data/site";

export const metadata: Metadata = { title: "Academics", description: "Explore Grey School Academy's curriculum, teaching and learning journey." };
export default function AcademicsPage() { return <>
  <PageHero eyebrow="Academics" title="Knowledge gives children confidence." intro="A carefully sequenced curriculum, taught with clarity and brought to life through questions, making, discussion and purposeful practice." image={images.library} imageAlt="A library filled with books and natural light" />
  <Section><Container><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr]"><SectionHeading eyebrow="Our approach" title="Strong foundations. Expansive thinking." intro="Our curriculum names what children should know, then creates the conditions in which that knowledge can become flexible, connected and genuinely useful." /><div className="border-l-2 border-growth pl-7 lg:mt-24"><p className="font-serif text-2xl italic leading-9 text-midnight">We teach for the moment when a child says, “I know something that might help.”</p></div></div></Container></Section>
  <Section id="stages" className="bg-sage/55"><Container><SectionHeading eyebrow="Ages 4–11" title="Three stages. One coherent education." /><div className="mt-14 space-y-20">{stages.map((stage,i) => <article key={stage.name} className="grid items-center gap-10 lg:grid-cols-2 lg:gap-20"><div className={`relative aspect-[3/2] ${i%2 ? "lg:order-2" : ""}`}><Image src={stage.image} alt={`${stage.name} pupils learning`} fill sizes="50vw" className="object-cover"/><span className="absolute left-0 top-0 bg-midnight px-5 py-3 text-xs font-bold uppercase tracking-[.15em] text-white">0{i+1} · {stage.ages}</span></div><div><h3 className="font-sans text-5xl font-semibold tracking-tight text-midnight">{stage.name}</h3><p className="mt-5 max-w-lg text-lg leading-8 text-slate">{stage.copy}</p><ul className="mt-7 space-y-3">{stage.priorities.map((p,n)=><li key={p} className="flex items-center gap-4 border-b border-growth/20 pb-3"><span className="text-xs font-bold text-growth">0{n+1}</span><span className="font-semibold">{p}</span></li>)}</ul></div></article>)}</div></Container></Section>
  <Section id="curriculum" className="bg-porcelain"><Container><SectionHeading eyebrow="Curriculum" title="Subjects that speak to one another." intro="Choose a subject to see the habits of mind and practical capabilities pupils develop."/><CurriculumExplorer/></Container></Section>
  <Section id="support"><Container><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-5"><SectionHeading eyebrow="Teaching & support" title="Attention changes what is possible." /></div><div className="grid gap-8 sm:grid-cols-2 lg:col-span-7">{[["Responsive teaching","Teachers use precise checks for understanding and adjust instruction before gaps grow."],["Learning support","Specialists work alongside class teachers, pupils and families with plans that are practical and joined up."],["Assessment with purpose","Assessment tells us what to teach next. Feedback is clear, timely and proportionate."],["Stretch and scholarship","Depth, not acceleration for its own sake: demanding texts, complex problems and authentic audiences."]].map(([t,c])=><div key={t} className="border-t border-midnight pt-5"><h3 className="font-sans text-xl font-semibold text-midnight">{t}</h3><p className="mt-3 text-sm leading-6 text-slate">{c}</p></div>)}</div></div></Container></Section>
  <section id="enrichment" className="relative min-h-[600px] text-white"><Image src={images.nature} alt="Outdoor learning beyond the classroom" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-midnight/70"/><Container className="relative flex min-h-[600px] items-center"><div className="max-w-3xl"><p className="eyebrow text-sage">Enrichment</p><h2 className="section-title">The world is part of the curriculum.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">Fieldwork, visiting experts, performance, competition and community projects allow pupils to use what they know where it matters.</p></div></Container></section>
  <AdmissionsPanel />
  </>; }
