import type { Metadata } from "next";
import Image from "next/image";
import { ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/editorial/page-hero";
import { AdmissionsPanel } from "@/components/editorial/admissions-panel";
import { Container, Eyebrow, Section, SectionHeading } from "@/components/core/container";
import { LinkArrow } from "@/components/core/button";
import { images, staff, values } from "@/data/site";

export const metadata: Metadata = { title: "About Grey", description: "Discover the purpose, people and values of Grey School Academy." };
export default function AboutPage() { return <>
  <PageHero eyebrow="About Grey" title="Education shaped around the whole child." intro="We are academically ambitious because we know children are capable—and deeply personal because no two children grow in quite the same way." image={images.teacher} imageAlt="Teacher supporting pupils in a bright classroom" />
  <Section id="purpose"><Container><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-7"><SectionHeading eyebrow="Our purpose" title="To build the knowledge and self-belief that make a life larger." /></div><div className="lg:col-span-5 lg:pt-24"><p className="text-lg leading-8 text-slate">Grey was founded on a simple conviction: excellent education can be both demanding and humane. Children thrive when expectations are clear, relationships are strong and learning feels consequential.</p><p className="mt-5 leading-7 text-slate">That conviction shapes our classrooms, our pastoral care and the way adults speak to children—and to one another.</p></div></div></Container></Section>
  <Section id="welcome" className="bg-porcelain"><Container><div className="grid items-center gap-14 lg:grid-cols-2 lg:gap-24"><div className="relative aspect-[4/5]"><Image src={images.child} alt="Headteacher Amelia Reed with pupils" fill sizes="50vw" className="object-cover" /></div><div><Eyebrow className="text-growth">Headteacher’s welcome</Eyebrow><blockquote className="font-serif text-[clamp(2rem,4vw,3.8rem)] italic leading-[1.1] text-midnight">“We take children seriously—their questions, their character and the person each is becoming.”</blockquote><p className="mt-8 leading-7 text-slate">A school should give children a calm place from which to be brave. At Grey, expert teaching sits alongside careful listening. We want pupils to leave us knowledgeable and articulate, but also generous, grounded and ready to participate.</p><p className="mt-6 font-serif text-2xl italic">Amelia Reed</p><p className="text-xs font-bold uppercase tracking-[.15em] text-growth">Headteacher</p></div></div></Container></Section>
  <Section><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Our story" title="Built with intention." /><div className="space-y-12 border-l border-hairline pl-8 md:pl-14">{[["2008","Grey opens with 42 pupils and a promise to know every child well."],["2015","A new library and science studio extend learning beyond conventional classroom boundaries."],["2021","The garden classroom and community partnership programme become part of every year group’s curriculum."],["Today","A purposeful, diverse school community of 280 pupils, still small enough for every name to matter."]].map(([year,text]) => <div key={year}><span className="text-xs font-bold tracking-widest text-growth">{year}</span><p className="mt-2 max-w-2xl text-lg leading-8 text-midnight">{text}</p></div>)}</div></div></Container></Section>
  <Section className="bg-sage/60"><Container><SectionHeading eyebrow="The Grey character" title="Values lived in small moments." /><div className="mt-14 border-t border-growth/30">{values.map((value,i) => <div key={value.name} className="grid items-baseline gap-3 border-b border-growth/30 py-6 md:grid-cols-[70px_1fr_1fr]"><span className="text-xs font-bold text-growth">0{i+1}</span><h3 className="font-sans text-3xl font-semibold tracking-tight text-midnight">{value.name}</h3><p className="max-w-lg text-sm leading-6 text-slate">{value.description}</p></div>)}</div></Container></Section>
  <Section id="people"><Container><SectionHeading eyebrow="Our people" title="Skilled teachers. Attentive adults." intro="Our leaders protect the conditions in which children and teachers do their best work: clarity, trust, scholarship and care." /><div className="mt-14 grid gap-5 md:grid-cols-3">{staff.map(person => <article key={person.name}><div className="relative aspect-[4/5] overflow-hidden"><Image src={person.image} alt={`${person.name}, ${person.role}`} fill sizes="33vw" className="object-cover grayscale-[15%]" /></div><h3 className="mt-5 font-sans text-xl font-semibold text-midnight">{person.name}</h3><p className="mt-1 text-sm text-slate">{person.role}</p></article>)}</div></Container></Section>
  <section className="border-y border-hairline bg-porcelain py-14"><Container><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="flex gap-5"><ShieldCheck className="h-9 w-9 text-growth"/><div><h2 className="font-sans text-2xl font-semibold text-midnight">Safeguarding comes first.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate">Every adult at Grey shares responsibility for protecting children and acting on concerns.</p></div></div><LinkArrow href="/safeguarding" className="text-scholastic">Read our safeguarding approach</LinkArrow></div></Container></section>
  <AdmissionsPanel />
  </>; }
