import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { HomeHero } from "@/components/home/home-hero";
import { CurriculumExplorer } from "@/components/home/curriculum-explorer";
import { Testimonials } from "@/components/home/testimonials";
import { StatsBand } from "@/components/home/stats-band";
import { InsideGreyToday } from "@/components/home/inside-grey-today";
import { LearningPurpose } from "@/components/home/learning-purpose";
import { LearningJourney } from "@/components/home/learning-journey";
import { StudentLifeMosaic } from "@/components/home/student-life-mosaic";
import { GalleryGrid } from "@/components/media/gallery-grid";
import { AdmissionsPanel } from "@/components/editorial/admissions-panel";
import { Button, LinkArrow } from "@/components/core/button";
import { Container, Eyebrow, Section, SectionHeading } from "@/components/core/container";
import { events, images, news } from "@/data/site";

export default function HomePage() {
  return <>
    <HomeHero />

    <Section id="welcome" className="relative overflow-hidden bg-cream">
      <Container><div className="grid gap-12 lg:grid-cols-12 lg:gap-8"><div className="lg:col-span-2"><Eyebrow className="text-growth">Welcome to Grey</Eyebrow></div><div className="lg:col-span-8"><h2 className="section-title max-w-5xl text-midnight">Every child should feel <span className="font-serif font-normal italic text-growth">known</span> before they are asked to be brave.</h2><div className="mt-10 grid gap-8 md:grid-cols-2"><p className="text-lg leading-8 text-ink">Grey School Academy is an international junior school shaped around the singular child—not an imagined average.</p><p className="leading-7 text-slate">We combine thoughtful teaching, personal attention and experiences rich enough to help young people become capable, kind and genuinely curious.</p></div><LinkArrow href="/about" className="mt-9 text-scholastic">Why families choose Grey</LinkArrow></div></div></Container>
      <div className="relative mx-auto mt-20 aspect-[16/8] min-h-[430px] max-w-[1600px] overflow-hidden"><Image src={images.teacher} alt="A teacher sharing an idea with a small group of pupils" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-midnight/60 via-transparent to-transparent" /><blockquote className="absolute bottom-8 left-5 max-w-lg border-l border-sage pl-5 font-serif text-2xl italic leading-tight text-white sm:bottom-12 sm:left-[10%] sm:text-4xl">“My teachers listen to the questions behind my question.”<cite className="mt-4 block font-sans text-[.65rem] not-italic uppercase tracking-[.16em] text-white/65">Mara · Year 5</cite></blockquote></div>
    </Section>

    <InsideGreyToday />

    <Section className="bg-sandstone">
      <Container><div className="grid items-stretch gap-0 lg:grid-cols-12"><div className="relative min-h-[560px] lg:col-span-5"><Image src={images.child} alt="A confident young pupil at Grey School Academy" fill sizes="(min-width: 1024px) 42vw, 100vw" className="object-cover object-center" /><span className="vertical-word absolute left-4 top-7 text-[.62rem] font-bold uppercase tracking-[.18em] text-white/80">Seen · heard · encouraged</span></div><div className="flex flex-col justify-center bg-cream px-7 py-14 sm:px-12 lg:col-span-7 lg:px-16 xl:px-20"><Eyebrow className="text-growth">From the Headteacher</Eyebrow><blockquote className="font-serif text-[clamp(2rem,3.7vw,3.65rem)] italic leading-[1.1] tracking-[-.025em] text-midnight">“Education should give children both roots and wings: the confidence to know who they are and the curiosity to discover what comes next.”</blockquote><p className="mt-8 max-w-xl leading-7 text-slate">At Grey, success is the growing capacity to think, contribute, recover from difficulty and take genuine delight in learning.</p><div className="mt-9 border-t border-midnight/15 pt-6"><p className="font-serif text-3xl italic text-midnight">Amelia Reed</p><p className="mt-1 text-[.65rem] font-bold uppercase tracking-[.16em] text-growth">Headteacher</p></div><LinkArrow href="/about#welcome" className="mt-7 text-scholastic">Read the Headteacher’s welcome</LinkArrow></div></div></Container>
    </Section>

    <StatsBand />
    <LearningPurpose />
    <LearningJourney />

    <Section id="curriculum" className="bg-porcelain"><Container><SectionHeading eyebrow="Curriculum" title="A broad education. Explored deeply." intro="Choose a subject to see how careful teaching, rich material and meaningful practice come together at Grey." /><CurriculumExplorer /></Container></Section>

    <section className="relative min-h-[760px] overflow-hidden text-white"><Image src={images.nature} alt="Pupils learning together outside the classroom" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-midnight/90 via-midnight/55 to-transparent" /><Container className="relative flex min-h-[760px] items-center"><div className="max-w-3xl py-24"><Eyebrow className="text-sage">Beyond the classroom</Eyebrow><h2 className="section-title text-white">Learning does not stop at the classroom door.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">Experiments spill into the garden. History leads to a museum. Music becomes performance. We design experiences that give knowledge somewhere real to go.</p><div className="mt-10 flex flex-wrap gap-2">{["Experiments", "Trips", "Outdoor learning", "Performance", "Projects"].map(item => <span key={item} className="border border-white/30 px-4 py-2 text-xs font-semibold">{item}</span>)}</div><Button href="/student-life" variant="light" className="mt-10" arrow>Life beyond lessons</Button></div></Container></section>

    <Section><Container><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-4"><div className="lg:sticky lg:top-36"><SectionHeading eyebrow="Student life" title="A school day should contain more than lessons." intro="Room to move, make, perform, lead, laugh and find a pursuit that feels entirely your own." /><LinkArrow href="/student-life" className="mt-8 text-scholastic">Discover student life</LinkArrow><blockquote className="mt-14 border-l border-gold pl-5 font-serif text-2xl italic leading-8 text-midnight">“The best days are when an idea starts in class and ends somewhere completely different.”<cite className="mt-3 block font-sans text-[.62rem] not-italic uppercase tracking-[.15em] text-slate">Noah · Year 6</cite></blockquote></div></div><StudentLifeMosaic /></div></Container></Section>

    <Section id="community" className="overflow-hidden bg-sage"><Container><div className="grid items-center gap-14 lg:grid-cols-12"><div className="relative min-h-[540px] lg:col-span-7"><Image src={images.community} alt="Pupils and teachers learning together in a diverse school community" fill sizes="(min-width:1024px) 58vw, 100vw" className="object-cover" /><div className="absolute -bottom-1 right-0 bg-midnight px-7 py-6 text-white"><strong className="font-serif text-3xl font-normal italic text-sage">Many perspectives.</strong><span className="mt-1 block text-[.62rem] uppercase tracking-[.16em] text-white/55">One generous community</span></div></div><div className="lg:col-span-5 lg:pl-8"><Eyebrow className="text-growth">Global community</Eyebrow><h2 className="section-title text-midnight">Rooted here. Open to the world.</h2><p className="mt-7 text-lg leading-8 text-slate">Our pupils bring different languages, family histories and ways of seeing. We make that diversity visible in what we read, whom we study and how we learn from one another.</p><blockquote className="mt-10 border-t border-growth/35 pt-7 font-serif text-2xl italic leading-8 text-midnight">“Belonging is not about becoming the same. It is knowing your difference is welcome.”<cite className="mt-4 block font-sans text-[.62rem] not-italic uppercase tracking-[.14em] text-growth">Daniel Okafor · Deputy Head</cite></blockquote></div></div></Container></Section>

    <Section className="bg-midnight text-white"><Container><Testimonials /></Container></Section>

    <Section><Container><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="From Grey" title="News with something to say." /><LinkArrow href="/news" className="text-scholastic">Visit the newsroom</LinkArrow></div><div className="mt-14 grid gap-8 lg:grid-cols-2">{news.map((article, index) => <article key={article.title} className={index === 0 ? "row-span-2" : "grid gap-6 sm:grid-cols-[.8fr_1.2fr]"}><Link href="/news" aria-label={`Read ${article.title}`} className={`group relative block overflow-hidden ${index === 0 ? "aspect-[4/3]" : "aspect-[4/3] sm:aspect-auto"}`}><Image src={article.image} alt="" fill sizes={index === 0 ? "(min-width:1024px) 50vw, 100vw" : "(min-width:1024px) 20vw, 100vw"} className="object-cover transition duration-500 group-hover:scale-[1.03]" /></Link><div className={index === 0 ? "pt-6" : "py-3"}><p className="text-xs font-bold uppercase tracking-[.14em] text-growth">{article.category} · {article.date}</p><h3 className={`mt-3 font-sans font-semibold leading-tight tracking-tight text-midnight ${index === 0 ? "text-3xl md:text-4xl" : "text-xl"}`}><Link href="/news" className="hover:text-scholastic">{article.title}</Link></h3><p className="mt-3 text-sm leading-6 text-slate">{article.excerpt}</p></div></article>)}</div></Container></Section>

    <Section id="events" className="bg-porcelain"><Container><div className="grid gap-12 lg:grid-cols-[.6fr_1.4fr]"><div><SectionHeading eyebrow="School calendar" title="Dates to know." /><LinkArrow href="/news#events" className="mt-8 text-scholastic">View school calendar</LinkArrow></div><div className="border-t border-midnight">{events.map(event => <Link href="/news#events" key={event.title} className="focus-ring group grid grid-cols-[70px_1fr_auto] items-center gap-5 border-b border-hairline py-6"><div><strong className="font-sans text-3xl font-semibold text-midnight">{event.day}</strong><span className="ml-1 text-xs font-bold text-growth">{event.month}</span></div><div><h3 className="font-sans text-lg font-semibold group-hover:text-scholastic">{event.title}</h3><p className="mt-1 text-xs text-slate">{event.time} · {event.audience}</p></div><ArrowUpRight className="h-5 w-5 text-slate transition group-hover:-translate-y-1 group-hover:translate-x-1" /></Link>)}</div></div></Container></Section>

    <Section><Container><div className="flex items-end justify-between"><SectionHeading eyebrow="A glimpse of Grey" title="Life, in the making." /><LinkArrow href="/gallery" className="hidden text-scholastic md:inline-flex">Explore the gallery</LinkArrow></div><div className="mt-12"><GalleryGrid preview /></div><LinkArrow href="/gallery" className="mt-7 text-scholastic md:hidden">Explore the gallery</LinkArrow></Container></Section>

    <AdmissionsPanel />
    <section className="bg-sage/60 py-16"><Container><div className="grid items-center gap-7 lg:grid-cols-[1.3fr_.7fr]"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-growth">Notes from Grey</p><h2 className="mt-3 font-sans text-3xl font-semibold tracking-tight text-midnight">A thoughtful update, once a month.</h2><p className="mt-2 text-sm text-slate">School stories, practical dates and ideas from our classrooms.</p></div><form className="flex flex-col gap-3 sm:flex-row"><label htmlFor="newsletter-email" className="sr-only">Email address</label><input id="newsletter-email" type="email" required placeholder="Email address" className="focus-ring min-h-12 flex-1 border border-midnight/20 bg-cream px-4 text-sm" /><button className="focus-ring min-h-12 bg-midnight px-6 font-sans text-sm font-bold text-white transition hover:bg-scholastic">Subscribe</button></form></div></Container></section>
  </>;
}
