import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { HomeHero } from "@/components/home/home-hero";
import { CurriculumExplorer } from "@/components/home/curriculum-explorer";
import { Testimonials } from "@/components/home/testimonials";
import { StatsBand } from "@/components/home/stats-band";
import { AdmissionsPanel } from "@/components/editorial/admissions-panel";
import { Button, LinkArrow } from "@/components/core/button";
import { Container, Eyebrow, Section, SectionHeading } from "@/components/core/container";
import { events, gallery, images, news, stages, values } from "@/data/site";

export default function HomePage() {
  return <>
    <HomeHero />

    <Section id="welcome" className="relative overflow-hidden bg-cream">
      <Container><div className="grid gap-12 lg:grid-cols-12 lg:gap-8"><div className="lg:col-span-2"><Eyebrow className="text-growth">Welcome to Grey</Eyebrow></div><div className="lg:col-span-8"><h2 className="section-title max-w-5xl text-midnight">Every child should feel <span className="font-serif font-normal italic text-growth">known</span> before they are asked to be brave.</h2><div className="mt-10 grid gap-8 md:grid-cols-2"><p className="text-lg leading-8 text-ink">Grey School Academy is an international junior school shaped around the singular child—not an imagined average.</p><p className="leading-7 text-slate">We combine thoughtful teaching, personal attention and experiences rich enough to help young people become capable, kind and genuinely curious.</p></div><LinkArrow href="/about" className="mt-9 text-scholastic">Why families choose Grey</LinkArrow></div></div></Container>
      <div className="relative mx-auto mt-20 aspect-[16/8] min-h-[430px] max-w-[1600px] overflow-hidden"><Image src={images.teacher} alt="A teacher sharing an idea with a small group of pupils" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-midnight/60 via-transparent to-transparent" /><blockquote className="absolute bottom-8 left-5 max-w-lg border-l border-sage pl-5 font-serif text-2xl italic leading-tight text-white sm:bottom-12 sm:left-[10%] sm:text-4xl">“My teachers listen to the questions behind my question.”<cite className="mt-4 block font-sans text-[.65rem] not-italic uppercase tracking-[.16em] text-white/65">Mara · Year 5</cite></blockquote></div>
    </Section>

    <Section className="bg-sandstone">
      <Container><div className="grid items-stretch gap-0 lg:grid-cols-12"><div className="relative min-h-[560px] lg:col-span-5"><Image src={images.child} alt="A confident young pupil at Grey School Academy" fill sizes="(min-width: 1024px) 42vw, 100vw" className="object-cover object-center" /><span className="vertical-word absolute left-4 top-7 text-[.62rem] font-bold uppercase tracking-[.18em] text-white/80">Seen · heard · encouraged</span></div><div className="flex flex-col justify-center bg-cream px-7 py-14 sm:px-12 lg:col-span-7 lg:px-16 xl:px-20"><Eyebrow className="text-growth">From the Headteacher</Eyebrow><blockquote className="font-serif text-[clamp(2rem,3.7vw,3.65rem)] italic leading-[1.1] tracking-[-.025em] text-midnight">“Education should give children both roots and wings: the confidence to know who they are and the curiosity to discover what comes next.”</blockquote><p className="mt-8 max-w-xl leading-7 text-slate">At Grey, success is the growing capacity to think, contribute, recover from difficulty and take genuine delight in learning.</p><div className="mt-9 border-t border-midnight/15 pt-6"><p className="font-serif text-3xl italic text-midnight">Amelia Reed</p><p className="mt-1 text-[.65rem] font-bold uppercase tracking-[.16em] text-growth">Headteacher</p></div><LinkArrow href="/about#welcome" className="mt-7 text-scholastic">Read the Headteacher’s welcome</LinkArrow></div></div></Container>
    </Section>

    <StatsBand />

    <Section className="bg-porcelain">
      <Container><div className="grid gap-14 lg:grid-cols-12 lg:gap-20"><div className="lg:col-span-5"><div className="lg:sticky lg:top-36"><SectionHeading eyebrow="Academic philosophy" title="Learning with purpose." intro="Knowledge matters. So does knowing what to do with it. We give children secure foundations, then invite them to question, connect, make and explain." /><p className="mt-10 border-l border-growth pl-6 font-serif text-2xl italic leading-9 text-midnight">“A precise intention, with room for an unexpected idea.”</p></div></div><div className="lg:col-span-7">{[["01", "Know", "Core knowledge gives children something substantial to think with.", images.reading], ["02", "Question", "Curiosity turns information into insight and memorable understanding.", images.science], ["03", "Contribute", "Communication and character help learning travel beyond the individual.", images.art]].map(([n, title, copy, image]) => <article key={title} className="grid gap-7 border-t border-midnight/15 py-10 sm:grid-cols-[1fr_180px] sm:items-center"><div><span className="text-[.65rem] font-bold tracking-[.16em] text-growth">{n}</span><h3 className="mt-5 font-sans text-4xl font-semibold tracking-tight text-midnight">{title}</h3><p className="mt-4 max-w-md leading-7 text-slate">{copy}</p></div><div className="relative aspect-[4/3] overflow-hidden"><Image src={image} alt="" fill sizes="180px" className="object-cover" /></div></article>)}</div></div></Container>
    </Section>

    <Section className="overflow-hidden bg-sage/55">
      <Container><SectionHeading eyebrow="The learning journey" title="Growing, one assured step at a time." intro="The years from four to eleven are a remarkable stretch of childhood. Each stage at Grey has its own pace, purpose and possibility." />
        <div className="relative mt-16 grid gap-8 lg:grid-cols-3 lg:gap-0 before:absolute before:left-0 before:right-0 before:top-7 before:hidden before:h-px before:bg-growth/40 lg:before:block">{stages.map((stage, i) => <article key={stage.name} className={`relative ${i > 0 ? "lg:pt-20" : ""} ${i === 2 ? "lg:pt-40" : ""}`}><div className="relative z-10 mb-7 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-growth font-sans text-xs font-bold text-white">0{i + 1}</span><span className="text-xs font-bold uppercase tracking-[.16em] text-growth">{stage.ages}</span></div><div className="relative aspect-[4/5] overflow-hidden lg:mr-7"><Image src={stage.image} alt={`${stage.name} stage pupils learning together`} fill sizes="(min-width: 1024px) 30vw, 100vw" className="object-cover transition duration-700 hover:scale-[1.03]" /></div><div className="relative -mt-12 ml-7 bg-cream p-7 lg:mr-0"><h3 className="font-sans text-4xl font-semibold tracking-tight text-midnight">{stage.name}</h3><p className="mt-4 text-sm leading-6 text-slate">{stage.copy}</p><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2">{stage.priorities.map(p => <span className="text-xs font-bold text-growth" key={p}>{p}</span>)}</div><LinkArrow href="/academics#stages" className="mt-6 text-scholastic">Explore this stage</LinkArrow></div></article>)}</div>
      </Container>
    </Section>

    <Section id="curriculum" className="bg-porcelain"><Container><SectionHeading eyebrow="Curriculum" title="A broad education. Explored deeply." intro="Choose a subject to see how careful teaching, rich material and meaningful practice come together at Grey." /><CurriculumExplorer /></Container></Section>

    <section className="relative min-h-[760px] overflow-hidden text-white"><Image src={images.nature} alt="Pupils learning together outside the classroom" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-midnight/90 via-midnight/55 to-transparent" /><Container className="relative flex min-h-[760px] items-center"><div className="max-w-3xl py-24"><Eyebrow className="text-sage">Beyond the classroom</Eyebrow><h2 className="section-title text-white">Learning does not stop at the classroom door.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">Experiments spill into the garden. History leads to a museum. Music becomes performance. We design experiences that give knowledge somewhere real to go.</p><div className="mt-10 flex flex-wrap gap-2">{["Experiments", "Trips", "Outdoor learning", "Performance", "Projects"].map(x => <span key={x} className="border border-white/30 px-4 py-2 text-xs font-semibold">{x}</span>)}</div><Button href="/student-life" variant="light" className="mt-10" arrow>Life beyond lessons</Button></div></Container></section>

    <Section><Container><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-4"><div className="lg:sticky lg:top-36"><SectionHeading eyebrow="Student life" title="A school day should contain more than lessons." intro="Room to move, make, perform, lead, laugh and find a pursuit that feels entirely your own." /><LinkArrow href="/student-life" className="mt-8 text-scholastic">Discover student life</LinkArrow><blockquote className="mt-14 border-l border-gold pl-5 font-serif text-2xl italic leading-8 text-midnight">“The best days are when an idea starts in class and ends somewhere completely different.”<cite className="mt-3 block font-sans text-[.62rem] not-italic uppercase tracking-[.15em] text-slate">Noah · Year 6</cite></blockquote></div></div><div className="grid grid-cols-2 gap-3 lg:col-span-8 lg:grid-cols-12">{[[images.sport,"Sport","col-span-2 lg:col-span-7 aspect-[16/10]"],[images.art,"Art","lg:col-span-5 row-span-2 min-h-[340px]"],[images.music,"Music","lg:col-span-4 aspect-square"],[images.library,"Reading","lg:col-span-3 aspect-square"]].map(([src,label,cls]) => <Link key={label} href="/student-life" className={`group relative overflow-hidden ${cls}`}><Image src={src} alt={`${label} at Grey School Academy`} fill sizes="(min-width:1024px) 40vw, 50vw" className="object-cover transition duration-700 group-hover:scale-[1.035]" /><span className="absolute inset-0 bg-gradient-to-t from-midnight/70 to-transparent" /><span className="absolute bottom-4 left-4 text-[.65rem] font-bold uppercase tracking-[.15em] text-white">{label}</span></Link>)}</div></div></Container></Section>

    <Section id="community" className="overflow-hidden bg-sage"><Container><div className="grid items-center gap-14 lg:grid-cols-12"><div className="relative min-h-[540px] lg:col-span-7"><Image src={images.community} alt="Pupils and teachers learning together in a diverse school community" fill sizes="(min-width:1024px) 58vw, 100vw" className="object-cover" /><div className="absolute -bottom-1 right-0 bg-midnight px-7 py-6 text-white"><strong className="font-serif text-3xl font-normal italic text-sage">Many perspectives.</strong><span className="mt-1 block text-[.62rem] uppercase tracking-[.16em] text-white/55">One generous community</span></div></div><div className="lg:col-span-5 lg:pl-8"><Eyebrow className="text-growth">Global community</Eyebrow><h2 className="section-title text-midnight">Rooted here. Open to the world.</h2><p className="mt-7 text-lg leading-8 text-slate">Our pupils bring different languages, family histories and ways of seeing. We make that diversity visible in what we read, whom we study and how we learn from one another.</p><blockquote className="mt-10 border-t border-growth/35 pt-7 font-serif text-2xl italic leading-8 text-midnight">“Belonging is not about becoming the same. It is knowing your difference is welcome.”<cite className="mt-4 block font-sans text-[.62rem] not-italic uppercase tracking-[.14em] text-growth">Daniel Okafor · Deputy Head</cite></blockquote></div></div></Container></Section>

    <Section className="bg-midnight text-white"><Container><Testimonials /></Container></Section>

    <Section><Container><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="From Grey" title="News with something to say." /><LinkArrow href="/news" className="text-scholastic">Visit the newsroom</LinkArrow></div><div className="mt-14 grid gap-8 lg:grid-cols-2">{news.map((article, i) => <article key={article.title} className={i === 0 ? "row-span-2" : "grid gap-6 sm:grid-cols-[.8fr_1.2fr]"}><Link href="/news" className={`group relative block overflow-hidden ${i === 0 ? "aspect-[4/3]" : "aspect-[4/3] sm:aspect-auto"}`}><Image src={article.image} alt="" fill sizes={i === 0 ? "(min-width:1024px) 50vw, 100vw" : "(min-width:1024px) 20vw, 100vw"} className="object-cover transition duration-500 group-hover:scale-[1.03]" /></Link><div className={i === 0 ? "pt-6" : "py-3"}><p className="text-xs font-bold uppercase tracking-[.14em] text-growth">{article.category} · {article.date}</p><h3 className={`mt-3 font-sans font-semibold leading-tight tracking-tight text-midnight ${i === 0 ? "text-3xl md:text-4xl" : "text-xl"}`}><Link href="/news" className="hover:text-scholastic">{article.title}</Link></h3><p className="mt-3 text-sm leading-6 text-slate">{article.excerpt}</p></div></article>)}</div></Container></Section>

    <Section id="events" className="bg-porcelain"><Container><div className="grid gap-12 lg:grid-cols-[.6fr_1.4fr]"><div><SectionHeading eyebrow="School calendar" title="Dates to know." /><LinkArrow href="/news#events" className="mt-8 text-scholastic">View school calendar</LinkArrow></div><div className="border-t border-midnight">{events.map(event => <Link href="/news#events" key={event.title} className="focus-ring group grid grid-cols-[70px_1fr_auto] items-center gap-5 border-b border-hairline py-6"><div><strong className="font-sans text-3xl font-semibold text-midnight">{event.day}</strong><span className="ml-1 text-xs font-bold text-growth">{event.month}</span></div><div><h3 className="font-sans text-lg font-semibold group-hover:text-scholastic">{event.title}</h3><p className="mt-1 text-xs text-slate">{event.time} · {event.audience}</p></div><ArrowUpRight className="h-5 w-5 text-slate transition group-hover:-translate-y-1 group-hover:translate-x-1" /></Link>)}</div></div></Container></Section>

    <Section><Container><div className="flex items-end justify-between"><SectionHeading eyebrow="A glimpse of Grey" title="Life, in the making." /><LinkArrow href="/gallery" className="hidden text-scholastic md:inline-flex">Explore the gallery</LinkArrow></div><div className="mt-12 grid auto-rows-[220px] grid-cols-2 gap-3 md:grid-cols-4">{gallery.slice(0,5).map((item,i) => <div key={item.src} className={`relative overflow-hidden ${i === 0 ? "col-span-2 row-span-2" : i === 1 ? "row-span-2" : ""}`}><Image src={item.src} alt={item.alt} fill sizes="(min-width:768px) 50vw, 100vw" className="object-cover" /></div>)}</div><LinkArrow href="/gallery" className="mt-7 text-scholastic md:hidden">Explore the gallery</LinkArrow></Container></Section>

    <AdmissionsPanel />
    <section className="bg-sage/60 py-16"><Container><div className="grid items-center gap-7 lg:grid-cols-[1.3fr_.7fr]"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-growth">Notes from Grey</p><h2 className="mt-3 font-sans text-3xl font-semibold tracking-tight text-midnight">A thoughtful update, once a month.</h2><p className="mt-2 text-sm text-slate">School stories, practical dates and ideas from our classrooms.</p></div><form className="flex flex-col gap-3 sm:flex-row"><label htmlFor="newsletter-email" className="sr-only">Email address</label><input id="newsletter-email" type="email" required placeholder="Email address" className="focus-ring min-h-12 flex-1 border border-midnight/20 bg-cream px-4 text-sm" /><button className="focus-ring min-h-12 bg-midnight px-6 font-sans text-sm font-bold text-white transition hover:bg-scholastic">Subscribe</button></form></div></Container></section>
  </>;
}
