import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { HomeHero } from "@/components/home/home-hero";
import { CurriculumExplorer } from "@/components/home/curriculum-explorer";
import { Testimonials } from "@/components/home/testimonials";
import { AdmissionsPanel } from "@/components/editorial/admissions-panel";
import { Button, LinkArrow } from "@/components/core/button";
import { Container, Eyebrow, Section, SectionHeading } from "@/components/core/container";
import { events, gallery, images, news, stages, values } from "@/data/site";

export default function HomePage() {
  return <>
    <HomeHero />

    <Section id="welcome" className="bg-cream">
      <Container>
        <div className="grid items-center gap-14 lg:grid-cols-12 lg:gap-10">
          <div className="lg:col-span-7"><Eyebrow className="text-growth">Welcome to Grey</Eyebrow><h2 className="section-title max-w-4xl text-midnight">Every child should feel <span className="font-serif font-normal italic text-growth">known</span> before they can feel challenged.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-slate">Grey School Academy combines thoughtful teaching, personal attention and rich experiences to help young people become capable, kind and confident learners.</p><LinkArrow href="/about" className="mt-8 text-scholastic">Why families choose Grey</LinkArrow></div>
          <div className="relative lg:col-span-5 lg:pl-10"><div className="relative aspect-[4/5] overflow-hidden"><Image src={images.teacher} alt="A Grey teacher giving pupils thoughtful individual guidance" fill sizes="(min-width: 1024px) 36vw, 90vw" className="object-cover" /></div><div className="absolute -bottom-8 -left-2 bg-midnight p-6 text-white sm:-left-8 sm:p-8"><span className="block font-serif text-4xl italic text-sage">4–11</span><span className="mt-1 block text-xs uppercase tracking-[.16em] text-white/70">One carefully connected journey</span></div></div>
        </div>
      </Container>
    </Section>

    <Section className="bg-porcelain">
      <Container>
        <div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:gap-24">
          <div className="relative min-h-[520px]"><Image src={images.child} alt="A confident young pupil at Grey School Academy" fill sizes="(min-width: 1024px) 42vw, 100vw" className="object-cover object-center" /><div className="absolute -bottom-1 -right-1 h-32 w-32 bg-sage/90" /></div>
          <div className="flex flex-col justify-center"><Eyebrow className="text-growth">From the Headteacher</Eyebrow><blockquote className="font-serif text-[clamp(2.1rem,4vw,4rem)] italic leading-[1.08] tracking-[-.03em] text-midnight">“Education should give children both roots and wings: the confidence to know who they are and the curiosity to discover what comes next.”</blockquote><p className="mt-8 max-w-xl leading-7 text-slate">At Grey, success is not one narrow destination. It is the growing capacity to think, contribute, recover from difficulty and take genuine delight in learning.</p><div className="mt-8"><p className="font-serif text-2xl italic text-midnight">Amelia Reed</p><p className="mt-1 text-xs font-bold uppercase tracking-[.15em] text-slate">Headteacher</p></div><LinkArrow href="/about#welcome" className="mt-8 text-scholastic">Read the Headteacher’s welcome</LinkArrow></div>
        </div>
      </Container>
    </Section>

    <section className="bg-midnight py-16 text-white"><Container><div className="grid grid-cols-2 gap-y-10 md:grid-cols-4">{[["12:1", "Pupil–teacher ratio"], ["20+", "Weekly clubs"], ["95%", "Parent satisfaction"], ["100%", "Known by name"]].map(([number, label], i) => <div key={label} className={`px-4 md:px-8 ${i > 0 ? "border-l border-white/15" : ""}`}><strong className="block font-sans text-[clamp(2.8rem,5vw,5.5rem)] font-medium tracking-[-.06em] text-sage">{number}</strong><span className="mt-2 block text-xs uppercase tracking-[.15em] text-white/60">{label}</span></div>)}</div></Container></section>

    <Section>
      <Container>
        <div className="grid gap-16 lg:grid-cols-12"><div className="lg:col-span-7"><SectionHeading eyebrow="Academic philosophy" title="Learning with purpose." intro="Knowledge matters. So does knowing what to do with it. We give children secure foundations, then invite them to question, connect, make and explain." /></div><div className="lg:col-span-5 lg:pt-24"><p className="border-l-2 border-growth pl-6 font-serif text-2xl italic leading-9 text-midnight">“A Grey lesson begins with a precise intention—and leaves room for an unexpected idea.”</p></div></div>
        <div className="mt-20 grid border-y border-hairline md:grid-cols-3">{[["01", "Know", "Core knowledge gives children something substantial to think with."], ["02", "Question", "Curiosity turns information into insight and memorable understanding."], ["03", "Contribute", "Communication and character help learning travel beyond the individual."]].map(([n, title, copy]) => <div key={title} className="border-b border-hairline py-9 md:border-b-0 md:border-r md:px-8 first:pl-0 last:border-r-0"><span className="text-xs font-bold text-growth">{n}</span><h3 className="mt-6 font-sans text-3xl font-semibold tracking-tight text-midnight">{title}</h3><p className="mt-4 max-w-sm leading-7 text-slate">{copy}</p></div>)}</div>
      </Container>
    </Section>

    <Section className="overflow-hidden bg-sage/55">
      <Container><SectionHeading eyebrow="The learning journey" title="Growing, one assured step at a time." intro="The years from four to eleven are a remarkable stretch of childhood. Each stage at Grey has its own pace, purpose and possibility." />
        <div className="relative mt-16 grid gap-8 lg:grid-cols-3 lg:gap-0 before:absolute before:left-0 before:right-0 before:top-7 before:hidden before:h-px before:bg-growth/40 lg:before:block">{stages.map((stage, i) => <article key={stage.name} className={`relative ${i > 0 ? "lg:pt-20" : ""} ${i === 2 ? "lg:pt-40" : ""}`}><div className="relative z-10 mb-7 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-growth font-sans text-xs font-bold text-white">0{i + 1}</span><span className="text-xs font-bold uppercase tracking-[.16em] text-growth">{stage.ages}</span></div><div className="relative aspect-[4/5] overflow-hidden lg:mr-7"><Image src={stage.image} alt={`${stage.name} stage pupils learning together`} fill sizes="(min-width: 1024px) 30vw, 100vw" className="object-cover transition duration-700 hover:scale-[1.03]" /></div><div className="relative -mt-12 ml-7 bg-cream p-7 lg:mr-0"><h3 className="font-sans text-4xl font-semibold tracking-tight text-midnight">{stage.name}</h3><p className="mt-4 text-sm leading-6 text-slate">{stage.copy}</p><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2">{stage.priorities.map(p => <span className="text-xs font-bold text-growth" key={p}>{p}</span>)}</div><LinkArrow href="/academics#stages" className="mt-6 text-scholastic">Explore this stage</LinkArrow></div></article>)}</div>
      </Container>
    </Section>

    <Section id="curriculum" className="bg-porcelain"><Container><SectionHeading eyebrow="Curriculum" title="A broad education. Explored deeply." intro="Choose a subject to see how careful teaching, rich material and meaningful practice come together at Grey." /><CurriculumExplorer /></Container></Section>

    <section className="relative min-h-[760px] overflow-hidden text-white"><Image src={images.nature} alt="Pupils learning together outside the classroom" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-midnight/90 via-midnight/55 to-transparent" /><Container className="relative flex min-h-[760px] items-center"><div className="max-w-3xl py-24"><Eyebrow className="text-sage">Beyond the classroom</Eyebrow><h2 className="section-title text-white">Learning does not stop at the classroom door.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">Experiments spill into the garden. History leads to a museum. Music becomes performance. We design experiences that give knowledge somewhere real to go.</p><div className="mt-10 flex flex-wrap gap-2">{["Experiments", "Trips", "Outdoor learning", "Performance", "Projects"].map(x => <span key={x} className="border border-white/30 px-4 py-2 text-xs font-semibold">{x}</span>)}</div><Button href="/student-life" variant="light" className="mt-10" arrow>Life beyond lessons</Button></div></Container></section>

    <Section><Container><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><SectionHeading eyebrow="Student life" title="A school day should contain more than lessons." intro="Room to move, make, perform, lead, laugh and find a pursuit that feels entirely your own." /><LinkArrow href="/student-life" className="mt-8 text-scholastic">Discover student life</LinkArrow></div><div className="grid grid-cols-2 gap-3 lg:col-span-7 lg:grid-cols-12">{[[images.sport,"Sport","col-span-2 lg:col-span-7 aspect-[16/10]"],[images.art,"Art","lg:col-span-5 row-span-2 min-h-[300px]"],[images.music,"Music","lg:col-span-4 aspect-square"],[images.library,"Reading","lg:col-span-3 aspect-square"]].map(([src,label,cls]) => <Link key={label} href="/student-life" className={`group relative overflow-hidden ${cls}`}><Image src={src} alt={`${label} at Grey School Academy`} fill sizes="(min-width:1024px) 40vw, 50vw" className="object-cover transition duration-700 group-hover:scale-[1.03]" /><span className="absolute inset-0 bg-gradient-to-t from-midnight/70 to-transparent" /><span className="absolute bottom-4 left-4 font-sans text-lg font-semibold text-white">{label}</span></Link>)}</div></div></Container></Section>

    <Section className="bg-midnight text-white"><Container><Testimonials /></Container></Section>

    <Section><Container><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="From Grey" title="News with something to say." /><LinkArrow href="/news" className="text-scholastic">Visit the newsroom</LinkArrow></div><div className="mt-14 grid gap-8 lg:grid-cols-2">{news.map((article, i) => <article key={article.title} className={i === 0 ? "row-span-2" : "grid gap-6 sm:grid-cols-[.8fr_1.2fr]"}><Link href="/news" className={`group relative block overflow-hidden ${i === 0 ? "aspect-[4/3]" : "aspect-[4/3] sm:aspect-auto"}`}><Image src={article.image} alt="" fill sizes={i === 0 ? "(min-width:1024px) 50vw, 100vw" : "(min-width:1024px) 20vw, 100vw"} className="object-cover transition duration-500 group-hover:scale-[1.03]" /></Link><div className={i === 0 ? "pt-6" : "py-3"}><p className="text-xs font-bold uppercase tracking-[.14em] text-growth">{article.category} · {article.date}</p><h3 className={`mt-3 font-sans font-semibold leading-tight tracking-tight text-midnight ${i === 0 ? "text-3xl md:text-4xl" : "text-xl"}`}><Link href="/news" className="hover:text-scholastic">{article.title}</Link></h3><p className="mt-3 text-sm leading-6 text-slate">{article.excerpt}</p></div></article>)}</div></Container></Section>

    <Section id="events" className="bg-porcelain"><Container><div className="grid gap-12 lg:grid-cols-[.6fr_1.4fr]"><div><SectionHeading eyebrow="School calendar" title="Dates to know." /><LinkArrow href="/news#events" className="mt-8 text-scholastic">View school calendar</LinkArrow></div><div className="border-t border-midnight">{events.map(event => <Link href="/news#events" key={event.title} className="focus-ring group grid grid-cols-[70px_1fr_auto] items-center gap-5 border-b border-hairline py-6"><div><strong className="font-sans text-3xl font-semibold text-midnight">{event.day}</strong><span className="ml-1 text-xs font-bold text-growth">{event.month}</span></div><div><h3 className="font-sans text-lg font-semibold group-hover:text-scholastic">{event.title}</h3><p className="mt-1 text-xs text-slate">{event.time} · {event.audience}</p></div><ArrowUpRight className="h-5 w-5 text-slate transition group-hover:-translate-y-1 group-hover:translate-x-1" /></Link>)}</div></div></Container></Section>

    <Section><Container><div className="flex items-end justify-between"><SectionHeading eyebrow="A glimpse of Grey" title="Life, in the making." /><LinkArrow href="/gallery" className="hidden text-scholastic md:inline-flex">Explore the gallery</LinkArrow></div><div className="mt-12 grid auto-rows-[220px] grid-cols-2 gap-3 md:grid-cols-4">{gallery.slice(0,5).map((item,i) => <div key={item.src} className={`relative overflow-hidden ${i === 0 ? "col-span-2 row-span-2" : i === 1 ? "row-span-2" : ""}`}><Image src={item.src} alt={item.alt} fill sizes="(min-width:768px) 50vw, 100vw" className="object-cover" /></div>)}</div><LinkArrow href="/gallery" className="mt-7 text-scholastic md:hidden">Explore the gallery</LinkArrow></Container></Section>

    <AdmissionsPanel />
    <section className="bg-sage/60 py-16"><Container><div className="grid items-center gap-7 lg:grid-cols-[1.3fr_.7fr]"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-growth">Notes from Grey</p><h2 className="mt-3 font-sans text-3xl font-semibold tracking-tight text-midnight">A thoughtful update, once a month.</h2><p className="mt-2 text-sm text-slate">School stories, practical dates and ideas from our classrooms.</p></div><form className="flex flex-col gap-3 sm:flex-row"><label htmlFor="newsletter-email" className="sr-only">Email address</label><input id="newsletter-email" type="email" required placeholder="Email address" className="focus-ring min-h-12 flex-1 border border-midnight/20 bg-cream px-4 text-sm" /><button className="focus-ring min-h-12 bg-midnight px-6 font-sans text-sm font-bold text-white transition hover:bg-scholastic">Subscribe</button></form></div></Container></section>
  </>;
}
