import type { Metadata } from "next";
import Image from "next/image";
import { AdmissionsPanel } from "@/components/editorial/admissions-panel";
import { PageHero } from "@/components/editorial/page-hero";
import { Container, Section, SectionHeading } from "@/components/core/container";
import { gallery, images } from "@/data/site";

export const metadata: Metadata = { title: "Student Life", description: "See the full, active and creative school day at Grey." };
const day = [["08:15","Arrive & connect","A calm welcome, conversation and time to settle."],["08:45","Morning learning","Focused teaching when minds are at their freshest."],["10:30","Break & play","Fresh air, friendship and serious games."],["11:00","Science discovery","Questions become practical investigations."],["12:30","Lunch","Shared tables, good food and time to talk."],["13:30","Creative learning","Art, music, design, drama and making."],["15:00","Clubs & activities","A different ending to almost every day."]];
export default function StudentLifePage(){ return <>
  <PageHero eyebrow="Student life" title="Childhood should be full of possibility." intro="A Grey day has shape and purpose, but also room for the unexpected friendship, new fascination or brave first attempt that children remember." image={images.sport} imageAlt="Children enjoying team sport outdoors" />
  <Section><Container><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-6"><SectionHeading eyebrow="More than lessons" title="Space to find your thing—and people to share it with."/></div><div className="lg:col-span-5 lg:col-start-8 lg:pt-24"><p className="text-lg leading-8 text-slate">The arts, sport, clubs, trips and leadership are not extras around the edge of school life. They are places where pupils discover discipline, delight, teamwork and a voice of their own.</p></div></div><div className="mt-16 grid auto-rows-[260px] grid-cols-2 gap-3 lg:grid-cols-4">{gallery.slice(0,6).map((item,i)=><div key={item.src} className={`relative overflow-hidden ${i===0?"col-span-2 row-span-2":i===3?"col-span-2":""}`}><Image src={item.src} alt={item.alt} fill sizes="50vw" className="object-cover"/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-midnight/80 to-transparent p-5 pt-14 text-sm font-bold text-white">{item.category}</span></div>)}</div></Container></Section>
  <Section className="bg-midnight text-white"><Container><SectionHeading eyebrow="A day at Grey" title="A rhythm children can rely on." intro="Predictable enough to feel secure. Varied enough to keep curiosity alive." light/><div className="mt-16 border-t border-white/20">{day.map(([time,title,copy],i)=><div key={time} className="grid gap-3 border-b border-white/20 py-6 sm:grid-cols-[100px_1fr_1fr] sm:items-center"><span className="font-sans text-2xl font-semibold text-sage">{time}</span><h3 className="font-sans text-xl font-semibold">{title}</h3><p className="text-sm leading-6 text-white/55">{copy}</p></div>)}</div></Container></Section>
  <Section><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Weekly programme" title="Something worth staying for."/><div className="overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left text-sm"><thead><tr className="border-b border-midnight"><th className="py-4">Day</th><th>Creative</th><th>Active</th><th>Curious</th></tr></thead><tbody>{[["Monday","Choir","Football","Chess"],["Tuesday","Ceramics","Swimming","Coding"],["Wednesday","Drama","Athletics","Nature club"],["Thursday","Orchestra","Basketball","Debate"],["Friday","Studio art","Dance","Young gardeners"]].map(row=><tr key={row[0]} className="border-b border-hairline">{row.map((cell,i)=><td key={cell} className={`py-5 ${i===0?"font-bold text-midnight":"text-slate"}`}>{cell}</td>)}</tr>)}</tbody></table><p className="mt-4 text-xs text-slate">Illustrative programme; activities rotate each term.</p></div></div></Container></Section>
  <Section className="bg-sage/55"><Container><div className="grid items-center gap-12 lg:grid-cols-2"><div className="relative aspect-[4/3]"><Image src={images.nature} alt="Children learning and caring for the outdoors" fill sizes="50vw" className="object-cover"/></div><div><SectionHeading eyebrow="Wellbeing & belonging" title="Known, heard and helped." intro="Class teachers hold the whole picture. House mentors add another trusted adult. Weekly circle time builds the language children need for friendship, disagreement and asking for help."/><ul className="mt-8 grid grid-cols-2 gap-3 text-sm font-semibold text-growth"><li>House belonging</li><li>Pupil leadership</li><li>Calm spaces</li><li>Pastoral check-ins</li></ul></div></div></Container></Section>
  <AdmissionsPanel/>
  </> }
